"""Structured models for AI plans, their validation results and agent responses."""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

from app.domain.intents import QUERY_INTENTS, Intent
from app.events.models import DeviceEvent

MAX_PLAN_ACTIONS = 12

# Intents the AI agent may use. Gesture-only intents (STOP, SELECT, TOGGLE, NONE) are excluded.
AI_DEVICE_INTENTS = frozenset(
    {
        Intent.TURN_ON,
        Intent.TURN_OFF,
        Intent.SET_BRIGHTNESS,
        Intent.SET_SPEED,
        Intent.SET_TEMPERATURE,
        Intent.LOCK_DOOR,
        Intent.UNLOCK_DOOR,
    }
)
AI_QUERY_INTENTS = QUERY_INTENTS
AI_INTENTS = AI_DEVICE_INTENTS | AI_QUERY_INTENTS


class ActionPlan(BaseModel):
    """The top-level shape every provider must return.

    Actions are kept raw here and validated one by one (:class:`PlannedAction`), so a
    single malformed action is rejected without discarding the rest of the plan.
    """

    model_config = ConfigDict(extra="forbid")

    message: str = Field(min_length=1, max_length=2000)
    actions: list[Any] = Field(default_factory=list, max_length=MAX_PLAN_ACTIONS)


class PlannedAction(BaseModel):
    """One action proposed by the AI. Strict: unknown fields are rejected."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    device_id: str | None = Field(default=None, min_length=1, max_length=64)
    intent: Intent
    parameters: dict[str, Any] = Field(default_factory=dict)


# Per-intent parameter schemas.
class NoParameters(BaseModel):
    model_config = ConfigDict(extra="forbid")


class ValueParameters(BaseModel):
    model_config = ConfigDict(extra="forbid")

    value: int = Field(strict=True)


class HistoryParameters(BaseModel):
    model_config = ConfigDict(extra="forbid")

    limit: int = Field(default=10, ge=1, le=50, strict=True)


PARAMETER_MODELS: dict[Intent, type[BaseModel]] = {
    Intent.SET_BRIGHTNESS: ValueParameters,
    Intent.SET_SPEED: ValueParameters,
    Intent.SET_TEMPERATURE: ValueParameters,
    Intent.GET_HISTORY: HistoryParameters,
}


class ActionStatus(StrEnum):
    EXECUTED = "executed"  # device command ran
    ANSWERED = "answered"  # read-only query
    REJECTED = "rejected"  # failed validation/policy; never executed
    FAILED = "failed"  # passed validation but the device command failed


class ActionResult(BaseModel):
    index: int
    device_id: str | None = None
    intent: str | None = None
    parameters: dict[str, Any] = Field(default_factory=dict)
    status: ActionStatus
    code: str | None = None
    reason: str | None = None
    device_action: str | None = None
    device_event_id: str | None = None
    previous_state: dict[str, Any] | None = None
    new_state: dict[str, Any] | None = None
    data: Any = None


class AgentResponse(BaseModel):
    interaction_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    request: str
    reply: str  # the planner's explanation (untrusted text)
    outcome: str  # what actually happened, generated by the backend
    provider: str
    plan_valid: bool
    actions: list[ActionResult] = Field(default_factory=list)
    device_events: list[DeviceEvent] = Field(default_factory=list)
    changed_devices: list[str] = Field(default_factory=list)
    any_rejected: bool = False
    errors: list[str] = Field(default_factory=list)
